BattleManager
CombatStates
Main BattleManager.mainState
Referenced by BattleManager, Start.
BeingFactory BattleManager.beingFactory
Referenced by BattleManager, Start.
List<Being> BattleManager.combatants
Referenced by Alone.CanThisBeUsed, Ability.CanThisBeUsed, NewRound, NextTurn, Start, StartCombat.
int BattleManager.currentElement
Referenced by NewRound, NextTurn, StartCombat.
int BattleManager.textSpeed
Referenced by StartTurn.
CombatStates BattleManager.currentState
void BattleManager.Start()
References beingFactory, combatants, mainState.
void BattleManager.NewRound()
References combatants, currentElement, StartTurn.
Referenced by NextTurn.
IEnumerator BattleManager.StartTurn(Being being)
References CalculateToHit, Being.selectedAbility, Being.selectedTargets, textSpeed.
Referenced by NewRound, StartCombat.
IEnumerator BattleManager.CalculateToHit(Being being, Ability ability, List< Being > targets)
References Ability.effects.
Referenced by StartTurn.
void BattleManager.Update()
void BattleManager.StartCombat()
References combatants, currentElement, StartTurn.
void BattleManager.NextTurn()
References combatants, currentElement, NewRound.
BattleManager.BattleManager(Main main, BeingFactory bf)
References beingFactory, mainState.