Being
Condition
bool Being.playerControlled
string Being.beingName
Referenced by GetStat, GetStatValue, SelectTargets.
List<Stat> Being.stats
Referenced by GetStat, GetStatValue.
List<StatModulation> Being.statModulations
Condition Being.condition
List<Behaviour> Being.behaviours
Referenced by SelectAnAbility.
List<Ability> Being.abilities
Referenced by GetUseableAbilities.
List<Ability> Being.useableAbilities
Referenced by SelectAnAbility.
Ability Being.selectedAbility
Referenced by SelectAnAbility, SelectTargets, BattleManager.StartTurn.
List<Being> Being.selectedTargets
Referenced by BattleManager.StartTurn.
int Being.GetStatValue(string stat, int subStat)
Returns the value of a substat, 0 = Max, 1 = Base, 2 = current
stats The name of the Stat value 0 = Max, 1 = Base, 2 = current
References beingName, stats.
Referenced by CompareTwoValues.CanThisBeUsed.
Stat Being.GetStat(string statName)
References beingName, stats.
Referenced by CostsMP.Use, Damage.Use, ModulateToHitSelf.Use.
void Being.GetUseableAbilities()
References abilities.
void Being.SelectAnAbility()
References behaviours, selectedAbility, useableAbilities.
void Being.SelectTargets(Ability ability)
References beingName, selectedAbility.